#!/bin/bash

# some, but not all, inspiration:
# https://github.com/do-community/automated-setups/blob/master/Ubuntu-18.04/initial_server_setup.sh
# https://github.com/potts99/Linux-Post-Install/blob/master/post-install.sh
# https://github.com/jasonheecs/ubuntu-server-setup

# wget https://raw.githubusercontent.com/koenhoeymans/dotfiles/master/ubuntu-setup
# chmod +x ubuntu-setup
# ./ubuntu-setup

set -euxo pipefail

USERNAME=koen
HOME_DIRECTORY=/home/$USERNAME

adduser $USERNAME --gecos ''
usermod -a -G sudo $USERNAME


apt-get update

# ssh
apt-get install openssh-server -y

mkdir --parents $HOME_DIRECTORY/.ssh

wget -O $HOME_DIRECTORY/.ssh/authorized_keys https://raw.githubusercontent.com/koenhoeymans/dotfiles/master/authorized_keys

chmod 0700 $HOME_DIRECTORY/.ssh
chmod 0600 $HOME_DIRECTORY/.ssh/authorized_keys
chown --recursive $USERNAME:$USERNAME $HOME_DIRECTORY/.ssh

sed -re 's/^(\#?)(PasswordAuthentication)([[:space:]]+)yes/\2\3no/' -i /etc/ssh/sshd_config
sed -re 's/^(\#?)(PermitRootLogin)([[:space:]]+)(.*)/PermitRootLogin no/' -i /etc/ssh/sshd_config

# firewall

ufw allow OpenSSH
ufw --force enable

# Fail2Ban install
apt-get install -y fail2ban
systemctl start fail2ban
systemctl enable fail2ban

# Automatic downloads of security updates
apt-get install unattended-upgrades apt-listchanges update-notifier-common

echo Unattended-Upgrade::Mail "koen@hoeymans.be"; >> /etc/apt/apt.conf.d/50unattended-upgrades
echo Unattended-Upgrade::Automatic-Reboot "true"; >> /etc/apt/apt.conf.d/50unattended-upgrades
echo email_address=koen@hoeymans.be >> /etc/apt/listchanges.conf
echo APT::Periodic::AutocleanInterval "7"; >> /etc/apt/apt.conf.d/20auto-upgrades

# timezone
ln -fs "/usr/share/zoneinfo/Europe/Brussels" /etc/localtime # https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1554806
dpkg-reconfigure -f noninteractive tzdata

# mail alerts

# adapted from: https://www.cyberciti.biz/faq/postfix-smtp-authentication-for-mail-servers/
# choose satellite system
# use system name
# mail.zxcs.nl:465
apt-get install mailutils postfix
read -sp 'password for koen@hoeymans.be:' mailpassword
echo 'mail.zxcs.nl koen@hoeymans.be:'$mailpassword > /etc/postfix/password
chown root:root /etc/postfix/password
chmod 0600 /etc/postfix/password
postmap hash:/etc/postfix/password
echo 'smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = hash:/etc/postfix/password
smtp_sasl_security_options =
smtp_tls_wrappermode = yes
smtp_tls_security_level = encrypt
' >> /etc/postfix/main.cf
/etc/init.d/postfix reload

mail -s 'new system set up' koen@hoeymans.be <<< 'now rebooting'

reboot
